### ISSUE TITLE
Alignment-specific tests fails on i386

### ISSUE THREAD

**Issue by nmeum** [TaylanUB/scheme-bytestructures#47] opened 2023-08-03 19:11 UTC
On i386 the tests fail (I ran into this with Guile Scheme):

```
$ make check
./pre-inst-env          \
  /usr/bin/guile --no-auto-compile              \
  ./run-tests.guile.scm
%%%% Starting test bytestructures  (Writing full log to "bytestructures.log")
run-tests.body.scm:194: FAIL ref1
Backtrace:
           7 (primitive-load "/home/soeren/src/aports/testing/guile-…")
In ice-9/eval.scm:
    619:8  6 (_ #f)
In ice-9/boot-9.scm:
    142:2  5 (dynamic-wind #<procedure 8555c0 at ice-9/eval.scm:330…> …)
    142:2  4 (dynamic-wind #<procedure 86f7f0 at ice-9/eval.scm:330…> …)
In ice-9/eval.scm:
    619:8  3 (_ #(#(#<directory (guile-user) cf690>)))
In ice-9/boot-9.scm:
    142:2  2 (dynamic-wind #<procedure 871a40 at ice-9/eval.scm:330…> …)
In ice-9/eval.scm:
    619:8  1 (_ #(#(#(#<directory (guile-user) cf690>)) #<variable…>))
In unknown file:
           0 (bytevector-u64-native-set! #vu8(0 0 0 0 0 0 0 0 65 1 …) …)

ERROR: In procedure bytevector-u64-native-set!:
In procedure bytevector-u64-native-set!: Value out of range: 8
make: *** [Makefile:779: check] Error 1
```

The following test case fails:

https://github.com/TaylanUB/scheme-bytestructures/blob/8f57febd63ac09e8ed528eefd656461a398b0b4d/run-tests.body.scm#L183-L194

My educated guess is that this because `bs` is not a packed struct and the way `bs` is packed on i386 differs from other architectures. Since the test is—as is—not portable it would probably be best to remove it?

Full build log: [bytestructures.log](https://github.com/TaylanUB/scheme-bytestructures/files/12254313/bytestructures.log)

**Comment by TaylanUB** [comment] 2024-06-07 21:40
The intent is to support i386 as well and I'd prefer to fix the test rather than remove it.

Here's what I think is happening. Sadly, I don't have a i386 system to test, so someone will have to verify it for me (or teach me how to emulate i386).

(CC @lechner who's been looking into this issue.)

First of all it's not actually the "ref1" test that fails. It's the call to `bytevector-u64-native-set!` that follows right after, which is not part of a test but rather the setup for the next test.

I guess SRFI 64 gets confused because an error is raised outside a test. Actually, it should report it as a failure of the encapsulating test-group IMO, and my own SRFI 64 implementation in [scheme-srfis](https://github.com/TaylanUB/scheme-srfis/) would have probably provided much better output, but anyway. (If only Guile had proper support for R7RS...)

The problem is probably that I use a constant value of `8` as the offset argument to `bytevector-u64-native-set!` on line 195, which is correct on platforms where 64-bit integers are 8-byte aligned, but on i386 they are in fact 4-byte aligned if I'm not mistaken.

The library actually knows the correct alignment (see `bytestructures/body/numeric.scm`) and allocates a bytevector of size 12 on i386. (Two bytes for the first union which contains a `uint16`, then two bytes of padding, then eight bytes for the second union.) Starting to write a 64-bit integer at position 8 then fails, since there's only 32 bits of space after that.

I'll change the test such that it should work regardless of the platform, and still actually tests whether the alignment is being calculated properly. After that it should pass on i386 as well.

**Comment by TaylanUB** [comment] 2024-06-07 22:02
Latest commit should fix this. I'll see how I can test this for i386 if nobody beats me to it...

**Comment by TaylanUB** [comment] 2024-06-07 22:58
Oh I'm stupid. There's nothing in the whole process of running these tests that actually depends on low-level platform details like alignment of integer types, because the tests don't interact with any C code.

The tests merely check whether the library is self-consistent with the platform-specific constants it defines. If I want to "emulate" i386, all I need to do is change some constants in `numeric.scm` and rerun the tests. They will succeed regardless of the constants not matching the platform I'm running on.

Maybe one day I'll actually add tests that run C code but not today. Anyhow.

I've modified the constants to "emulate" i386 and was able to reproduce the test failure on the version 2.0.1. I've then observed that the latest commit indeed resolves the failure.

Release 2.0.2 with the fix is imminent, so I'm closing this issue. Please reopen if I was somehow wrong and it still fails on an actual i386 system.

**Closed by TaylanUB** 2024-06-07 22:58 UTC
